name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: generate body
        run: echo "# my appended test body" > RELEASE_BODY.md
      - name: update release
        id: update_release
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: RELEASE_BODY.md
          is_append_body: true
